#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
!pip install numpy

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vec=np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
siz=np.random.rand(5,3,2)
siz

array([[[0.00665862, 0.72171374],
        [0.40944257, 0.15810279],
        [0.67040632, 0.32342083]],

       [[0.1528113 , 0.53649167],
        [0.31647909, 0.6822112 ],
        [0.49148257, 0.53295383]],

       [[0.93850677, 0.0573849 ],
        [0.34524823, 0.88858145],
        [0.91279294, 0.713579  ]],

       [[0.09052076, 0.75332701],
        [0.06767832, 0.55410124],
        [0.30942489, 0.95367202]],

       [[0.59630411, 0.55849807],
        [0.43317165, 0.45669983],
        [0.35231486, 0.44716625]]])

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
import pandas as pd

In [6]:
from numpy.random import rand

In [7]:
import numpy as np

In [8]:
vec=np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
vec=[4]=1
vec

SyntaxError: cannot assign to literal (<ipython-input-9-97df1fc10791>, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
a=[::-1]
a

SyntaxError: invalid syntax (<ipython-input-7-7e44b38b9f56>, line 1)

In [10]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
val=np.arange(9).reshape(3,3)
val

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
ind=np.random.rand(3,5)
ind

array([[0.69845948, 0.39018637, 0.73382948, 0.25403639, 0.8376034 ],
       [0.11267864, 0.92688583, 0.13668648, 0.73984228, 0.28556243],
       [0.00375321, 0.72315358, 0.34072529, 0.63615714, 0.4704163 ]])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
f=np.zeros((3,3))
i,j=np.indices(f.shape)

f[i==j]=1
f[i==j-1]=1
f[i==j-2]=1


In [14]:
f

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
c=np.random.rand(3,3,3)
c

array([[[0.35756087, 0.20329219, 0.56694499],
        [0.77846923, 0.17939338, 0.54788421],
        [0.43132432, 0.50537281, 0.54223084]],

       [[0.65168979, 0.05515837, 0.33429596],
        [0.65909274, 0.10491934, 0.65769745],
        [0.75089223, 0.54822887, 0.22972699]],

       [[0.63838099, 0.2310595 , 0.43558888],
        [0.49227992, 0.13342104, 0.2886217 ],
        [0.88721314, 0.30698819, 0.02138026]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
d=np.random.rand(10,10)
d

array([[0.36112724, 0.4556716 , 0.18977147, 0.31352016, 0.56763398,
        0.12970551, 0.14699096, 0.57453686, 0.84555872, 0.11780952],
       [0.47428513, 0.64300908, 0.60128107, 0.82149263, 0.11690669,
        0.47450191, 0.43326738, 0.32264063, 0.11016864, 0.2003727 ],
       [0.23843078, 0.44036101, 0.88250753, 0.48140623, 0.63222044,
        0.29179681, 0.91549533, 0.50035823, 0.56653466, 0.82270313],
       [0.59304319, 0.04604884, 0.13763948, 0.91777509, 0.92091725,
        0.02860818, 0.54243545, 0.13833532, 0.32472624, 0.79942842],
       [0.81712459, 0.7499304 , 0.7086307 , 0.20252679, 0.5652356 ,
        0.28983207, 0.92131903, 0.10053076, 0.26340904, 0.9103251 ],
       [0.96055507, 0.31466688, 0.53439236, 0.64591468, 0.78382029,
        0.40067716, 0.84621646, 0.17743501, 0.0684169 , 0.35697876],
       [0.72803451, 0.26159151, 0.29352409, 0.97650058, 0.68579019,
        0.83104724, 0.61878191, 0.94050567, 0.07546883, 0.0405416 ],
       [0.13008765, 0.88780155, 0.6585025

In [15]:
d=[d min] & [d max]
d

SyntaxError: invalid syntax (<ipython-input-15-53a26eea1e09>, line 1)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
#mean=sum/count
m=np.arange(30)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
sum=np.sum(m)
sum

435

In [43]:
mean=sum/30
mean

14.5

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [73]:
n=np.zeros((5,5))

i,j=np.indices(n.shape)

n[i==j]=1
n[i==j+5]=1

In [74]:
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
0 * np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
np.nan in set([np.nan])
0.3==3*0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [83]:
mex=np.arange(5,5)
i,j=np.indices(mex.shape)
mex[i==j]=1
mex[i==j-1]=2
mex[i==j-2]=3
mex[i==j-3]=4

ValueError: not enough values to unpack (expected 2, got 1)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [15]:
x=np.zeros((8,8),dtype=int)
x=[1::2,::2]=1
x=[::2,1::2]=1
for i in range(8):
    for j in range(8):
        print(x[i][j], end = '')
    print()
n=8



SyntaxError: invalid syntax (<ipython-input-15-810a63a52e5d>, line 2)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)