In [1]:
import pandas as pd

In [2]:
import numpy as np


In [3]:
from numpy.random import rand

In [5]:
a=np.arange(20).reshape(5,4)

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
b=np.zeros((3,3))

In [8]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
c=np.random.rand()
d=np.random.rand()

In [10]:
mul=np.multiply(c,d)

In [11]:
mul

0.16051573293756827

In [14]:
b=np.zeros((10))
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
b[4]=1

In [16]:
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#conditional construct
x='light'
if x=='light':
    print('welcome')
else:
    ('nome')


welcome


In [26]:
mul=int(input('user num'))
lst=1
for i in range(1,mul):
    lst=lst*i
print(lst)
        
        

user num10
362880


In [53]:
sum=[1,2,3,4,5]
sum_add=0
for num in sum:
    sum_add=sum_add + i
print(sum_add)

25


In [31]:
sum=int(input('user num'))
lst_sum=0
for i in range(1,sum):
    lst_sum=lst_sum+i
print(lst_sum)


user num6
15


In [54]:
fox=int(input('user num'))
hen=[num+1 for num in fox]
print(hen)

user num4


TypeError: 'int' object is not iterable

In [34]:
hen=[1,2,3,4,5]
fox=[]
for num in hen:
    fox.append(num+1)
print(fox)

[2, 3, 4, 5, 6]


In [37]:
hen=[num for num in range(10)]
print(hen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [38]:
hen[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [40]:
hen=np.arange(2,5)

In [41]:
hen

array([2, 3, 4])

In [42]:
hen

array([2, 3, 4])

In [46]:
hen=[num for num in range(10)]
hen

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
hen

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]