In [1]:
import numpy as np

In [3]:
a=np.random.rand(2,3)
a

array([[0.2862646 , 0.7816253 , 0.79409887],
       [0.25290542, 0.86622245, 0.56987934]])

In [5]:
b=np.zeros((4,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
b[6]=2
b

array([1., 1., 1., 1., 1., 1., 2., 1., 1., 1.])

In [9]:
b.reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
c=np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
c[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
c.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
gam1=np.random.rand(10)
gam2=np.random.rand(10)



In [35]:
add=np.add(gam1,gam2)
add

array([1.06833349, 0.70554658, 0.4562883 , 0.75269556, 1.3370041 ,
       0.95879256, 1.43928659, 0.93923173, 1.44723538, 1.04672086])

In [38]:
sub=np.subtract(gam1,gam2)
sub

array([ 0.01548391,  0.16231057, -0.36702055, -0.39873388, -0.52790879,
       -0.61269664,  0.23738837, -0.1433055 ,  0.40754602,  0.81476277])

In [41]:
dot=np.dot(gam1,gam2)
dot


2.345844536539295